Updated: build config
biscuitdb/biscuitdb pull request #10
Opened 2021-08-11 07:35 UTC by noob77777

# Updates build files and read me

## Description

## Remaining tasks

- [ ] Fix Build issues for MacOS

## Further work
Update build for MacOS

2021-08-11 07:51 UTC, TheSYNcoder commented
Suggestion : 

Let's have one commit message per pull request. Can be done by ``` git commit --amend```
We can add this to the docs.

2021-08-11 08:25 UTC, noob77777 commented
> 
> 
> Suggestion :
> 
> Let's have one commit message per pull request. Can be done by ` git commit --amend`
> We can add this to the docs.

We will be defaulting to squash and merge.

2021-08-11 09:32 UTC, bisakhmondal commented
> > Suggestion :
> > Let's have one commit message per pull request. Can be done by ` git commit --amend`
> > We can add this to the docs.
> 
> We will be defaulting to squash and merge.

Agree +1
with amend you can't cherry-pick

2021-08-12 14:45 UTC, bisakhmondal approved these changes
\lgtm

2021-08-12 14:47 UTC, bisakhmondal requested changes

2021-08-12 14:47 UTC, bisakhmondal commented on codecov.yml
> +  - "third_party"
Minor change
Add the following directories
```
build_support
script
docs
.github
```

2021-08-12 14:47 UTC, merged

2021-08-12 14:51 UTC, bisakhmondal commented on codecov.yml
> +  - "third_party"
cool then